package com.shjn.model;
// Generated 2017-8-23 17:10:04 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * Cxdj generated by hbm2java
 */
public class Cxdj implements java.io.Serializable {

	private Integer id;
	private String organization;
	private String disciplinary;
	private Date revocationDate;
	private Date createTimestamp;
	private Date updateTimestamp;

	public Cxdj() {
	}

	public Cxdj(Date createTimestamp, Date updateTimestamp) {
		this.createTimestamp = createTimestamp;
		this.updateTimestamp = updateTimestamp;
	}

	public Cxdj(String organization, String disciplinary, Date revocationDate, Date createTimestamp,
			Date updateTimestamp) {
		this.organization = organization;
		this.disciplinary = disciplinary;
		this.revocationDate = revocationDate;
		this.createTimestamp = createTimestamp;
		this.updateTimestamp = updateTimestamp;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getOrganization() {
		return this.organization;
	}

	public void setOrganization(String organization) {
		this.organization = organization;
	}

	public String getDisciplinary() {
		return this.disciplinary;
	}

	public void setDisciplinary(String disciplinary) {
		this.disciplinary = disciplinary;
	}

	public Date getRevocationDate() {
		return this.revocationDate;
	}

	public void setRevocationDate(Date revocationDate) {
		this.revocationDate = revocationDate;
	}

	public Date getCreateTimestamp() {
		return this.createTimestamp;
	}

	public void setCreateTimestamp(Date createTimestamp) {
		this.createTimestamp = createTimestamp;
	}

	public Date getUpdateTimestamp() {
		return this.updateTimestamp;
	}

	public void setUpdateTimestamp(Date updateTimestamp) {
		this.updateTimestamp = updateTimestamp;
	}

}
