package com.shjn.model;
// Generated 2017-8-23 17:10:04 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * FundAccountDetail generated by hbm2java
 */
public class FundAccountDetail implements java.io.Serializable {

	private Integer id;
	private String fundAccountId;
	private String registerCode;
	private String manager;
	private String trusteeName;
	private Date registerDate;
	private String contractPeriod;
	private Double initialScale;
	private Boolean classification;
	private Integer investorsNumber;
	private String otherProductType;
	private Date createTimestamp;
	private Date updateTimestamp;

	public FundAccountDetail() {
	}

	public FundAccountDetail(Date createTimestamp, Date updateTimestamp) {
		this.createTimestamp = createTimestamp;
		this.updateTimestamp = updateTimestamp;
	}

	public FundAccountDetail(String fundAccountId, String registerCode, String manager, String trusteeName,
			Date registerDate, String contractPeriod, Double initialScale, Boolean classification,
			Integer investorsNumber, String otherProductType, Date createTimestamp, Date updateTimestamp) {
		this.fundAccountId = fundAccountId;
		this.registerCode = registerCode;
		this.manager = manager;
		this.trusteeName = trusteeName;
		this.registerDate = registerDate;
		this.contractPeriod = contractPeriod;
		this.initialScale = initialScale;
		this.classification = classification;
		this.investorsNumber = investorsNumber;
		this.otherProductType = otherProductType;
		this.createTimestamp = createTimestamp;
		this.updateTimestamp = updateTimestamp;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getFundAccountId() {
		return this.fundAccountId;
	}

	public void setFundAccountId(String fundAccountId) {
		this.fundAccountId = fundAccountId;
	}

	public String getRegisterCode() {
		return this.registerCode;
	}

	public void setRegisterCode(String registerCode) {
		this.registerCode = registerCode;
	}

	public String getManager() {
		return this.manager;
	}

	public void setManager(String manager) {
		this.manager = manager;
	}

	public String getTrusteeName() {
		return this.trusteeName;
	}

	public void setTrusteeName(String trusteeName) {
		this.trusteeName = trusteeName;
	}

	public Date getRegisterDate() {
		return this.registerDate;
	}

	public void setRegisterDate(Date registerDate) {
		this.registerDate = registerDate;
	}

	public String getContractPeriod() {
		return this.contractPeriod;
	}

	public void setContractPeriod(String contractPeriod) {
		this.contractPeriod = contractPeriod;
	}

	public Double getInitialScale() {
		return this.initialScale;
	}

	public void setInitialScale(Double initialScale) {
		this.initialScale = initialScale;
	}

	public Boolean getClassification() {
		return this.classification;
	}

	public void setClassification(Boolean classification) {
		this.classification = classification;
	}

	public Integer getInvestorsNumber() {
		return this.investorsNumber;
	}

	public void setInvestorsNumber(Integer investorsNumber) {
		this.investorsNumber = investorsNumber;
	}

	public String getOtherProductType() {
		return this.otherProductType;
	}

	public void setOtherProductType(String otherProductType) {
		this.otherProductType = otherProductType;
	}

	public Date getCreateTimestamp() {
		return this.createTimestamp;
	}

	public void setCreateTimestamp(Date createTimestamp) {
		this.createTimestamp = createTimestamp;
	}

	public Date getUpdateTimestamp() {
		return this.updateTimestamp;
	}

	public void setUpdateTimestamp(Date updateTimestamp) {
		this.updateTimestamp = updateTimestamp;
	}

}
