package com.shjn.model;
// Generated 2017-8-23 17:10:04 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * Fund generated by hbm2java
 */
public class Fund implements java.io.Serializable {

	private Integer id;
	private Long fundId;
	private String fundName;
	private String managerName;
	private Date establishDate;
	private Date putOnRecordDate;
	private Boolean lastQuarterUpdate;
	private Boolean containClassification;
	private Boolean containStructured;
	private String url;
	private Date createTimestamp;
	private Date updateTimestamp;

	public Fund() {
	}

	public Fund(Date createTimestamp, Date updateTimestamp) {
		this.createTimestamp = createTimestamp;
		this.updateTimestamp = updateTimestamp;
	}

	public Fund(Long fundId, String fundName, String managerName, Date establishDate, Date putOnRecordDate,
			Boolean lastQuarterUpdate, Boolean containClassification, Boolean containStructured, String url,
			Date createTimestamp, Date updateTimestamp) {
		this.fundId = fundId;
		this.fundName = fundName;
		this.managerName = managerName;
		this.establishDate = establishDate;
		this.putOnRecordDate = putOnRecordDate;
		this.lastQuarterUpdate = lastQuarterUpdate;
		this.containClassification = containClassification;
		this.containStructured = containStructured;
		this.url = url;
		this.createTimestamp = createTimestamp;
		this.updateTimestamp = updateTimestamp;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Long getFundId() {
		return this.fundId;
	}

	public void setFundId(Long fundId) {
		this.fundId = fundId;
	}

	public String getFundName() {
		return this.fundName;
	}

	public void setFundName(String fundName) {
		this.fundName = fundName;
	}

	public String getManagerName() {
		return this.managerName;
	}

	public void setManagerName(String managerName) {
		this.managerName = managerName;
	}

	public Date getEstablishDate() {
		return this.establishDate;
	}

	public void setEstablishDate(Date establishDate) {
		this.establishDate = establishDate;
	}

	public Date getPutOnRecordDate() {
		return this.putOnRecordDate;
	}

	public void setPutOnRecordDate(Date putOnRecordDate) {
		this.putOnRecordDate = putOnRecordDate;
	}

	public Boolean getLastQuarterUpdate() {
		return this.lastQuarterUpdate;
	}

	public void setLastQuarterUpdate(Boolean lastQuarterUpdate) {
		this.lastQuarterUpdate = lastQuarterUpdate;
	}

	public Boolean getContainClassification() {
		return this.containClassification;
	}

	public void setContainClassification(Boolean containClassification) {
		this.containClassification = containClassification;
	}

	public Boolean getContainStructured() {
		return this.containStructured;
	}

	public void setContainStructured(Boolean containStructured) {
		this.containStructured = containStructured;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public Date getCreateTimestamp() {
		return this.createTimestamp;
	}

	public void setCreateTimestamp(Date createTimestamp) {
		this.createTimestamp = createTimestamp;
	}

	public Date getUpdateTimestamp() {
		return this.updateTimestamp;
	}

	public void setUpdateTimestamp(Date updateTimestamp) {
		this.updateTimestamp = updateTimestamp;
	}

}
