package com.shjn.model;
// Generated 2017-8-23 17:10:04 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * FundDetail generated by hbm2java
 */
public class FundDetail implements java.io.Serializable {

	private Integer id;
	private Long fundId;
	private String fundNo;
	private Date establishDate;
	private Date putOnRecordDate;
	private Boolean putOnRecordPhase;
	private String fundType;
	private String currency;
	private Integer managerType;
	private String trusteeName;
	private String mainInvestment;
	private Integer workingState;
	private Date lastUpdated;
	private String specialNote;
	private String informationDisclosure;
	private Date createTimestamp;
	private Date updateTimestamp;

	public FundDetail() {
	}

	public FundDetail(Date createTimestamp, Date updateTimestamp) {
		this.createTimestamp = createTimestamp;
		this.updateTimestamp = updateTimestamp;
	}

	public FundDetail(Long fundId, String fundNo, Date establishDate, Date putOnRecordDate, Boolean putOnRecordPhase,
			String fundType, String currency, Integer managerType, String trusteeName, String mainInvestment,
			Integer workingState, Date lastUpdated, String specialNote, String informationDisclosure,
			Date createTimestamp, Date updateTimestamp) {
		this.fundId = fundId;
		this.fundNo = fundNo;
		this.establishDate = establishDate;
		this.putOnRecordDate = putOnRecordDate;
		this.putOnRecordPhase = putOnRecordPhase;
		this.fundType = fundType;
		this.currency = currency;
		this.managerType = managerType;
		this.trusteeName = trusteeName;
		this.mainInvestment = mainInvestment;
		this.workingState = workingState;
		this.lastUpdated = lastUpdated;
		this.specialNote = specialNote;
		this.informationDisclosure = informationDisclosure;
		this.createTimestamp = createTimestamp;
		this.updateTimestamp = updateTimestamp;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Long getFundId() {
		return this.fundId;
	}

	public void setFundId(Long fundId) {
		this.fundId = fundId;
	}

	public String getFundNo() {
		return this.fundNo;
	}

	public void setFundNo(String fundNo) {
		this.fundNo = fundNo;
	}

	public Date getEstablishDate() {
		return this.establishDate;
	}

	public void setEstablishDate(Date establishDate) {
		this.establishDate = establishDate;
	}

	public Date getPutOnRecordDate() {
		return this.putOnRecordDate;
	}

	public void setPutOnRecordDate(Date putOnRecordDate) {
		this.putOnRecordDate = putOnRecordDate;
	}

	public Boolean getPutOnRecordPhase() {
		return this.putOnRecordPhase;
	}

	public void setPutOnRecordPhase(Boolean putOnRecordPhase) {
		this.putOnRecordPhase = putOnRecordPhase;
	}

	public String getFundType() {
		return this.fundType;
	}

	public void setFundType(String fundType) {
		this.fundType = fundType;
	}

	public String getCurrency() {
		return this.currency;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}

	public Integer getManagerType() {
		return this.managerType;
	}

	public void setManagerType(Integer managerType) {
		this.managerType = managerType;
	}

	public String getTrusteeName() {
		return this.trusteeName;
	}

	public void setTrusteeName(String trusteeName) {
		this.trusteeName = trusteeName;
	}

	public String getMainInvestment() {
		return this.mainInvestment;
	}

	public void setMainInvestment(String mainInvestment) {
		this.mainInvestment = mainInvestment;
	}

	public Integer getWorkingState() {
		return this.workingState;
	}

	public void setWorkingState(Integer workingState) {
		this.workingState = workingState;
	}

	public Date getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

	public String getSpecialNote() {
		return this.specialNote;
	}

	public void setSpecialNote(String specialNote) {
		this.specialNote = specialNote;
	}

	public String getInformationDisclosure() {
		return this.informationDisclosure;
	}

	public void setInformationDisclosure(String informationDisclosure) {
		this.informationDisclosure = informationDisclosure;
	}

	public Date getCreateTimestamp() {
		return this.createTimestamp;
	}

	public void setCreateTimestamp(Date createTimestamp) {
		this.createTimestamp = createTimestamp;
	}

	public Date getUpdateTimestamp() {
		return this.updateTimestamp;
	}

	public void setUpdateTimestamp(Date updateTimestamp) {
		this.updateTimestamp = updateTimestamp;
	}

}
