package com.shjn.model;
// Generated 2017-8-23 17:10:04 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * Hmd generated by hbm2java
 */
public class Hmd implements java.io.Serializable {

	private Integer id;
	private String name;
	private String organization;
	private String disciplinary;
	private Date revocationTime;
	private Date createTimestamp;
	private Date updateTimestamp;

	public Hmd() {
	}

	public Hmd(Date createTimestamp, Date updateTimestamp) {
		this.createTimestamp = createTimestamp;
		this.updateTimestamp = updateTimestamp;
	}

	public Hmd(String name, String organization, String disciplinary, Date revocationTime, Date createTimestamp,
			Date updateTimestamp) {
		this.name = name;
		this.organization = organization;
		this.disciplinary = disciplinary;
		this.revocationTime = revocationTime;
		this.createTimestamp = createTimestamp;
		this.updateTimestamp = updateTimestamp;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getOrganization() {
		return this.organization;
	}

	public void setOrganization(String organization) {
		this.organization = organization;
	}

	public String getDisciplinary() {
		return this.disciplinary;
	}

	public void setDisciplinary(String disciplinary) {
		this.disciplinary = disciplinary;
	}

	public Date getRevocationTime() {
		return this.revocationTime;
	}

	public void setRevocationTime(Date revocationTime) {
		this.revocationTime = revocationTime;
	}

	public Date getCreateTimestamp() {
		return this.createTimestamp;
	}

	public void setCreateTimestamp(Date createTimestamp) {
		this.createTimestamp = createTimestamp;
	}

	public Date getUpdateTimestamp() {
		return this.updateTimestamp;
	}

	public void setUpdateTimestamp(Date updateTimestamp) {
		this.updateTimestamp = updateTimestamp;
	}

}
