package com.shjn.model;
// Generated 2017-8-23 17:10:04 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * ManagerDetail generated by hbm2java
 */
public class ManagerDetail implements java.io.Serializable {

	private Integer id;
	private Long managerId;
	private String managerNameC;
	private String managerNameE;
	private String orgCode;
	private String registerAddress;
	private String officeAddress;
	private Double registerCapital;
	private Double paidCapital;
	private Double registerCapitalUsd;
	private Double paidCapitalUsd;
	private Double paidCapitalRatio;
	private String enterpriseNature;
	private String primaryInvestType;
	private String otherBusinessApplications;
	private Integer employeesNumber;
	private String orgUrl;
	private Boolean member;
	private String memberType;
	private Date joinTime;
	private String legalOpinion;
	private String lawOffice;
	private String lawyer;
	private Boolean manageScalaZero;
	private Boolean oneYearManageScalaZero;
	private Boolean handInUnderRegister25p;
	private Boolean handInLe100w;
	private Integer fundScale1;
	private Integer fundScale2;
	private Integer fundScale3;
	private Integer fundScale4;
	private Integer fundScale5;
	private Boolean faithInfo1;
	private Boolean faithInfo2;
	private Boolean faithInfo3;
	private Boolean faithInfo4;
	private Boolean faithInfo5;
	private Boolean faithInfo6;
	private Boolean noQualifications;
	private String legalRepresentative;
	private String generalManager;
	private String riskControlManager;
	private Date createTimestamp;
	private Date updateTimestamp;

	public ManagerDetail() {
	}

	public ManagerDetail(Date createTimestamp, Date updateTimestamp) {
		this.createTimestamp = createTimestamp;
		this.updateTimestamp = updateTimestamp;
	}

	public ManagerDetail(Long managerId, String managerNameC, String managerNameE, String orgCode,
			String registerAddress, String officeAddress, Double registerCapital, Double paidCapital,
			Double registerCapitalUsd, Double paidCapitalUsd, Double paidCapitalRatio, String enterpriseNature,
			String primaryInvestType, String otherBusinessApplications, Integer employeesNumber, String orgUrl,
			Boolean member, String memberType, Date joinTime, String legalOpinion, String lawOffice, String lawyer,
			Boolean manageScalaZero, Boolean oneYearManageScalaZero, Boolean handInUnderRegister25p,
			Boolean handInLe100w, Integer fundScale1, Integer fundScale2, Integer fundScale3, Integer fundScale4,
			Integer fundScale5, Boolean faithInfo1, Boolean faithInfo2, Boolean faithInfo3, Boolean faithInfo4,
			Boolean faithInfo5, Boolean faithInfo6, Boolean noQualifications, String legalRepresentative,
			String generalManager, String riskControlManager, Date createTimestamp, Date updateTimestamp) {
		this.managerId = managerId;
		this.managerNameC = managerNameC;
		this.managerNameE = managerNameE;
		this.orgCode = orgCode;
		this.registerAddress = registerAddress;
		this.officeAddress = officeAddress;
		this.registerCapital = registerCapital;
		this.paidCapital = paidCapital;
		this.registerCapitalUsd = registerCapitalUsd;
		this.paidCapitalUsd = paidCapitalUsd;
		this.paidCapitalRatio = paidCapitalRatio;
		this.enterpriseNature = enterpriseNature;
		this.primaryInvestType = primaryInvestType;
		this.otherBusinessApplications = otherBusinessApplications;
		this.employeesNumber = employeesNumber;
		this.orgUrl = orgUrl;
		this.member = member;
		this.memberType = memberType;
		this.joinTime = joinTime;
		this.legalOpinion = legalOpinion;
		this.lawOffice = lawOffice;
		this.lawyer = lawyer;
		this.manageScalaZero = manageScalaZero;
		this.oneYearManageScalaZero = oneYearManageScalaZero;
		this.handInUnderRegister25p = handInUnderRegister25p;
		this.handInLe100w = handInLe100w;
		this.fundScale1 = fundScale1;
		this.fundScale2 = fundScale2;
		this.fundScale3 = fundScale3;
		this.fundScale4 = fundScale4;
		this.fundScale5 = fundScale5;
		this.faithInfo1 = faithInfo1;
		this.faithInfo2 = faithInfo2;
		this.faithInfo3 = faithInfo3;
		this.faithInfo4 = faithInfo4;
		this.faithInfo5 = faithInfo5;
		this.faithInfo6 = faithInfo6;
		this.noQualifications = noQualifications;
		this.legalRepresentative = legalRepresentative;
		this.generalManager = generalManager;
		this.riskControlManager = riskControlManager;
		this.createTimestamp = createTimestamp;
		this.updateTimestamp = updateTimestamp;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Long getManagerId() {
		return this.managerId;
	}

	public void setManagerId(Long managerId) {
		this.managerId = managerId;
	}

	public String getManagerNameC() {
		return this.managerNameC;
	}

	public void setManagerNameC(String managerNameC) {
		this.managerNameC = managerNameC;
	}

	public String getManagerNameE() {
		return this.managerNameE;
	}

	public void setManagerNameE(String managerNameE) {
		this.managerNameE = managerNameE;
	}

	public String getOrgCode() {
		return this.orgCode;
	}

	public void setOrgCode(String orgCode) {
		this.orgCode = orgCode;
	}

	public String getRegisterAddress() {
		return this.registerAddress;
	}

	public void setRegisterAddress(String registerAddress) {
		this.registerAddress = registerAddress;
	}

	public String getOfficeAddress() {
		return this.officeAddress;
	}

	public void setOfficeAddress(String officeAddress) {
		this.officeAddress = officeAddress;
	}

	public Double getRegisterCapital() {
		return this.registerCapital;
	}

	public void setRegisterCapital(Double registerCapital) {
		this.registerCapital = registerCapital;
	}

	public Double getPaidCapital() {
		return this.paidCapital;
	}

	public void setPaidCapital(Double paidCapital) {
		this.paidCapital = paidCapital;
	}

	public Double getRegisterCapitalUsd() {
		return this.registerCapitalUsd;
	}

	public void setRegisterCapitalUsd(Double registerCapitalUsd) {
		this.registerCapitalUsd = registerCapitalUsd;
	}

	public Double getPaidCapitalUsd() {
		return this.paidCapitalUsd;
	}

	public void setPaidCapitalUsd(Double paidCapitalUsd) {
		this.paidCapitalUsd = paidCapitalUsd;
	}

	public Double getPaidCapitalRatio() {
		return this.paidCapitalRatio;
	}

	public void setPaidCapitalRatio(Double paidCapitalRatio) {
		this.paidCapitalRatio = paidCapitalRatio;
	}

	public String getEnterpriseNature() {
		return this.enterpriseNature;
	}

	public void setEnterpriseNature(String enterpriseNature) {
		this.enterpriseNature = enterpriseNature;
	}

	public String getPrimaryInvestType() {
		return this.primaryInvestType;
	}

	public void setPrimaryInvestType(String primaryInvestType) {
		this.primaryInvestType = primaryInvestType;
	}

	public String getOtherBusinessApplications() {
		return this.otherBusinessApplications;
	}

	public void setOtherBusinessApplications(String otherBusinessApplications) {
		this.otherBusinessApplications = otherBusinessApplications;
	}

	public Integer getEmployeesNumber() {
		return this.employeesNumber;
	}

	public void setEmployeesNumber(Integer employeesNumber) {
		this.employeesNumber = employeesNumber;
	}

	public String getOrgUrl() {
		return this.orgUrl;
	}

	public void setOrgUrl(String orgUrl) {
		this.orgUrl = orgUrl;
	}

	public Boolean getMember() {
		return this.member;
	}

	public void setMember(Boolean member) {
		this.member = member;
	}

	public String getMemberType() {
		return this.memberType;
	}

	public void setMemberType(String memberType) {
		this.memberType = memberType;
	}

	public Date getJoinTime() {
		return this.joinTime;
	}

	public void setJoinTime(Date joinTime) {
		this.joinTime = joinTime;
	}

	public String getLegalOpinion() {
		return this.legalOpinion;
	}

	public void setLegalOpinion(String legalOpinion) {
		this.legalOpinion = legalOpinion;
	}

	public String getLawOffice() {
		return this.lawOffice;
	}

	public void setLawOffice(String lawOffice) {
		this.lawOffice = lawOffice;
	}

	public String getLawyer() {
		return this.lawyer;
	}

	public void setLawyer(String lawyer) {
		this.lawyer = lawyer;
	}

	public Boolean getManageScalaZero() {
		return this.manageScalaZero;
	}

	public void setManageScalaZero(Boolean manageScalaZero) {
		this.manageScalaZero = manageScalaZero;
	}

	public Boolean getOneYearManageScalaZero() {
		return this.oneYearManageScalaZero;
	}

	public void setOneYearManageScalaZero(Boolean oneYearManageScalaZero) {
		this.oneYearManageScalaZero = oneYearManageScalaZero;
	}

	public Boolean getHandInUnderRegister25p() {
		return this.handInUnderRegister25p;
	}

	public void setHandInUnderRegister25p(Boolean handInUnderRegister25p) {
		this.handInUnderRegister25p = handInUnderRegister25p;
	}

	public Boolean getHandInLe100w() {
		return this.handInLe100w;
	}

	public void setHandInLe100w(Boolean handInLe100w) {
		this.handInLe100w = handInLe100w;
	}

	public Integer getFundScale1() {
		return this.fundScale1;
	}

	public void setFundScale1(Integer fundScale1) {
		this.fundScale1 = fundScale1;
	}

	public Integer getFundScale2() {
		return this.fundScale2;
	}

	public void setFundScale2(Integer fundScale2) {
		this.fundScale2 = fundScale2;
	}

	public Integer getFundScale3() {
		return this.fundScale3;
	}

	public void setFundScale3(Integer fundScale3) {
		this.fundScale3 = fundScale3;
	}

	public Integer getFundScale4() {
		return this.fundScale4;
	}

	public void setFundScale4(Integer fundScale4) {
		this.fundScale4 = fundScale4;
	}

	public Integer getFundScale5() {
		return this.fundScale5;
	}

	public void setFundScale5(Integer fundScale5) {
		this.fundScale5 = fundScale5;
	}

	public Boolean getFaithInfo1() {
		return this.faithInfo1;
	}

	public void setFaithInfo1(Boolean faithInfo1) {
		this.faithInfo1 = faithInfo1;
	}

	public Boolean getFaithInfo2() {
		return this.faithInfo2;
	}

	public void setFaithInfo2(Boolean faithInfo2) {
		this.faithInfo2 = faithInfo2;
	}

	public Boolean getFaithInfo3() {
		return this.faithInfo3;
	}

	public void setFaithInfo3(Boolean faithInfo3) {
		this.faithInfo3 = faithInfo3;
	}

	public Boolean getFaithInfo4() {
		return this.faithInfo4;
	}

	public void setFaithInfo4(Boolean faithInfo4) {
		this.faithInfo4 = faithInfo4;
	}

	public Boolean getFaithInfo5() {
		return this.faithInfo5;
	}

	public void setFaithInfo5(Boolean faithInfo5) {
		this.faithInfo5 = faithInfo5;
	}

	public Boolean getFaithInfo6() {
		return this.faithInfo6;
	}

	public void setFaithInfo6(Boolean faithInfo6) {
		this.faithInfo6 = faithInfo6;
	}

	public Boolean getNoQualifications() {
		return this.noQualifications;
	}

	public void setNoQualifications(Boolean noQualifications) {
		this.noQualifications = noQualifications;
	}

	public String getLegalRepresentative() {
		return this.legalRepresentative;
	}

	public void setLegalRepresentative(String legalRepresentative) {
		this.legalRepresentative = legalRepresentative;
	}

	public String getGeneralManager() {
		return this.generalManager;
	}

	public void setGeneralManager(String generalManager) {
		this.generalManager = generalManager;
	}

	public String getRiskControlManager() {
		return this.riskControlManager;
	}

	public void setRiskControlManager(String riskControlManager) {
		this.riskControlManager = riskControlManager;
	}

	public Date getCreateTimestamp() {
		return this.createTimestamp;
	}

	public void setCreateTimestamp(Date createTimestamp) {
		this.createTimestamp = createTimestamp;
	}

	public Date getUpdateTimestamp() {
		return this.updateTimestamp;
	}

	public void setUpdateTimestamp(Date updateTimestamp) {
		this.updateTimestamp = updateTimestamp;
	}

}
