package com.shjn.model;
// Generated 2017-8-23 17:10:04 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * Manager generated by hbm2java
 */
public class Manager implements java.io.Serializable {

	private Integer id;
	private long managerId;
	private String managerNameC;
	private String artificialPersonName;
	private String primaryInvestType;
	private String registerProvince;
	private String registerNo;
	private Date establishDate;
	private Date registerDate;
	private String url;
	private Double fundScale;
	private Integer fundCount;
	private Date createTimestamp;
	private Date updateTimestamp;

	public Manager() {
	}

	public Manager(long managerId, String managerNameC, Date createTimestamp, Date updateTimestamp) {
		this.managerId = managerId;
		this.managerNameC = managerNameC;
		this.createTimestamp = createTimestamp;
		this.updateTimestamp = updateTimestamp;
	}

	public Manager(long managerId, String managerNameC, String artificialPersonName, String primaryInvestType,
			String registerProvince, String registerNo, Date establishDate, Date registerDate, String url,
			Double fundScale, Integer fundCount, Date createTimestamp, Date updateTimestamp) {
		this.managerId = managerId;
		this.managerNameC = managerNameC;
		this.artificialPersonName = artificialPersonName;
		this.primaryInvestType = primaryInvestType;
		this.registerProvince = registerProvince;
		this.registerNo = registerNo;
		this.establishDate = establishDate;
		this.registerDate = registerDate;
		this.url = url;
		this.fundScale = fundScale;
		this.fundCount = fundCount;
		this.createTimestamp = createTimestamp;
		this.updateTimestamp = updateTimestamp;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public long getManagerId() {
		return this.managerId;
	}

	public void setManagerId(long managerId) {
		this.managerId = managerId;
	}

	public String getManagerNameC() {
		return this.managerNameC;
	}

	public void setManagerNameC(String managerNameC) {
		this.managerNameC = managerNameC;
	}

	public String getArtificialPersonName() {
		return this.artificialPersonName;
	}

	public void setArtificialPersonName(String artificialPersonName) {
		this.artificialPersonName = artificialPersonName;
	}

	public String getPrimaryInvestType() {
		return this.primaryInvestType;
	}

	public void setPrimaryInvestType(String primaryInvestType) {
		this.primaryInvestType = primaryInvestType;
	}

	public String getRegisterProvince() {
		return this.registerProvince;
	}

	public void setRegisterProvince(String registerProvince) {
		this.registerProvince = registerProvince;
	}

	public String getRegisterNo() {
		return this.registerNo;
	}

	public void setRegisterNo(String registerNo) {
		this.registerNo = registerNo;
	}

	public Date getEstablishDate() {
		return this.establishDate;
	}

	public void setEstablishDate(Date establishDate) {
		this.establishDate = establishDate;
	}

	public Date getRegisterDate() {
		return this.registerDate;
	}

	public void setRegisterDate(Date registerDate) {
		this.registerDate = registerDate;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public Double getFundScale() {
		return this.fundScale;
	}

	public void setFundScale(Double fundScale) {
		this.fundScale = fundScale;
	}

	public Integer getFundCount() {
		return this.fundCount;
	}

	public void setFundCount(Integer fundCount) {
		this.fundCount = fundCount;
	}

	public Date getCreateTimestamp() {
		return this.createTimestamp;
	}

	public void setCreateTimestamp(Date createTimestamp) {
		this.createTimestamp = createTimestamp;
	}

	public Date getUpdateTimestamp() {
		return this.updateTimestamp;
	}

	public void setUpdateTimestamp(Date updateTimestamp) {
		this.updateTimestamp = updateTimestamp;
	}

}
