package com.shjn.model;
// Generated 2017-8-23 17:10:04 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * Zq generated by hbm2java
 */
public class Zq implements java.io.Serializable {

	private Integer id;
	private Long mpiId;
	private String productCode;
	private String productName;
	private String managerName;
	private Date createDate;
	private Boolean containClassification;
	private Boolean containStructured;
	private Date createTimestamp;
	private Date updateTimestamp;

	public Zq() {
	}

	public Zq(Date createTimestamp, Date updateTimestamp) {
		this.createTimestamp = createTimestamp;
		this.updateTimestamp = updateTimestamp;
	}

	public Zq(Long mpiId, String productCode, String productName, String managerName, Date createDate,
			Boolean containClassification, Boolean containStructured, Date createTimestamp, Date updateTimestamp) {
		this.mpiId = mpiId;
		this.productCode = productCode;
		this.productName = productName;
		this.managerName = managerName;
		this.createDate = createDate;
		this.containClassification = containClassification;
		this.containStructured = containStructured;
		this.createTimestamp = createTimestamp;
		this.updateTimestamp = updateTimestamp;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Long getMpiId() {
		return this.mpiId;
	}

	public void setMpiId(Long mpiId) {
		this.mpiId = mpiId;
	}

	public String getProductCode() {
		return this.productCode;
	}

	public void setProductCode(String productCode) {
		this.productCode = productCode;
	}

	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	public String getManagerName() {
		return this.managerName;
	}

	public void setManagerName(String managerName) {
		this.managerName = managerName;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Boolean getContainClassification() {
		return this.containClassification;
	}

	public void setContainClassification(Boolean containClassification) {
		this.containClassification = containClassification;
	}

	public Boolean getContainStructured() {
		return this.containStructured;
	}

	public void setContainStructured(Boolean containStructured) {
		this.containStructured = containStructured;
	}

	public Date getCreateTimestamp() {
		return this.createTimestamp;
	}

	public void setCreateTimestamp(Date createTimestamp) {
		this.createTimestamp = createTimestamp;
	}

	public Date getUpdateTimestamp() {
		return this.updateTimestamp;
	}

	public void setUpdateTimestamp(Date updateTimestamp) {
		this.updateTimestamp = updateTimestamp;
	}

}
