package com.shjn.model;
// Generated 2017-8-23 17:10:04 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * ZqDetail generated by hbm2java
 */
public class ZqDetail implements java.io.Serializable {

	private Integer id;
	private Long mpiId;
	private String productCode;
	private String managerName;
	private Date createDate;
	private String expiryDate;
	private String investmentType;
	private Boolean classification;
	private String management;
	private Double establishScale;
	private Integer householdsNumber;
	private String trusteeship;
	private String sra;
	private Date createTimestamp;
	private Date updateTimestamp;

	public ZqDetail() {
	}

	public ZqDetail(Date createTimestamp, Date updateTimestamp) {
		this.createTimestamp = createTimestamp;
		this.updateTimestamp = updateTimestamp;
	}

	public ZqDetail(Long mpiId, String productCode, String managerName, Date createDate, String expiryDate,
			String investmentType, Boolean classification, String management, Double establishScale,
			Integer householdsNumber, String trusteeship, String sra, Date createTimestamp, Date updateTimestamp) {
		this.mpiId = mpiId;
		this.productCode = productCode;
		this.managerName = managerName;
		this.createDate = createDate;
		this.expiryDate = expiryDate;
		this.investmentType = investmentType;
		this.classification = classification;
		this.management = management;
		this.establishScale = establishScale;
		this.householdsNumber = householdsNumber;
		this.trusteeship = trusteeship;
		this.sra = sra;
		this.createTimestamp = createTimestamp;
		this.updateTimestamp = updateTimestamp;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Long getMpiId() {
		return this.mpiId;
	}

	public void setMpiId(Long mpiId) {
		this.mpiId = mpiId;
	}

	public String getProductCode() {
		return this.productCode;
	}

	public void setProductCode(String productCode) {
		this.productCode = productCode;
	}

	public String getManagerName() {
		return this.managerName;
	}

	public void setManagerName(String managerName) {
		this.managerName = managerName;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public String getExpiryDate() {
		return this.expiryDate;
	}

	public void setExpiryDate(String expiryDate) {
		this.expiryDate = expiryDate;
	}

	public String getInvestmentType() {
		return this.investmentType;
	}

	public void setInvestmentType(String investmentType) {
		this.investmentType = investmentType;
	}

	public Boolean getClassification() {
		return this.classification;
	}

	public void setClassification(Boolean classification) {
		this.classification = classification;
	}

	public String getManagement() {
		return this.management;
	}

	public void setManagement(String management) {
		this.management = management;
	}

	public Double getEstablishScale() {
		return this.establishScale;
	}

	public void setEstablishScale(Double establishScale) {
		this.establishScale = establishScale;
	}

	public Integer getHouseholdsNumber() {
		return this.householdsNumber;
	}

	public void setHouseholdsNumber(Integer householdsNumber) {
		this.householdsNumber = householdsNumber;
	}

	public String getTrusteeship() {
		return this.trusteeship;
	}

	public void setTrusteeship(String trusteeship) {
		this.trusteeship = trusteeship;
	}

	public String getSra() {
		return this.sra;
	}

	public void setSra(String sra) {
		this.sra = sra;
	}

	public Date getCreateTimestamp() {
		return this.createTimestamp;
	}

	public void setCreateTimestamp(Date createTimestamp) {
		this.createTimestamp = createTimestamp;
	}

	public Date getUpdateTimestamp() {
		return this.updateTimestamp;
	}

	public void setUpdateTimestamp(Date updateTimestamp) {
		this.updateTimestamp = updateTimestamp;
	}

}
